/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2pJrvALZwGJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Chivo } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/components/ui/button"
import { CardContent, Card } from "@/components/components/ui/card"
import { Label } from "@/components/components/ui/label"
import { Input } from "@/components/components/ui/input"
import { Textarea } from "@/components/components/ui/textarea"

export function Main() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-4 px-6 md:px-12">
        <div className="container mx-auto flex justify-between items-center">
          <Link className="flex items-center gap-2 text-xl font-bold" href="#">
            <img
              alt="John Doe"
              className="rounded-full"
              height={40}
              src="/placeholder.svg"
              style={{
                aspectRatio: "40/40",
                objectFit: "cover",
              }}
              width={40}
            />
            John Doe
          </Link>
          <nav className="hidden md:flex space-x-6">
            <Link className="hover:text-gray-400" href="#">
              Home
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Personal Projects
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Work Projects
            </Link>
            <Link className="hover:text-gray-400" href="#">
              About
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Contact
            </Link>
          </nav>
          <Button className="md:hidden" size="sm" variant="outline">
            <MenuIcon className="w-5 h-5" />
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-gray-100 py-12 md:py-20">
          <div className="container mx-auto px-6 md:px-12 grid md:grid-cols-2 gap-8 items-center">
            <div>
              <h1 className="text-3xl md:text-4xl font-bold mb-4">Hi, I'm John Doe</h1>
              <p className="text-gray-600 mb-6">
                I'm a software engineer with a passion for building beautiful and functional web applications. I have
                experience in both front-end and back-end development, and I'm always eager to learn new technologies.
              </p>
              <div className="flex space-x-4">
                <Link
                  className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
                  href="#"
                >
                  View Personal Projects
                </Link>
                <Link
                  className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
                  href="#"
                >
                  View Work Projects
                </Link>
                <Link
                  className="inline-flex items-center justify-center px-4 py-2 text-gray-900 rounded-md hover:bg-gray-200 transition-colors"
                  href="#"
                >
                  Learn More
                </Link>
              </div>
            </div>
            <div className="hidden md:block">
              <img
                alt="John Doe"
                className="rounded-full"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-8">Personal Projects</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <img
                  alt="Project Thumbnail"
                  className="rounded-t-md"
                  height={225}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold mb-2">Task Management App</h3>
                  <p className="text-gray-600 mb-4">
                    A web application that helps users manage their tasks and projects.
                  </p>
                  <div className="flex items-center gap-2 mb-4">
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">React</div>
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">Node.js</div>
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">MongoDB</div>
                  </div>
                  <Link
                    className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
                    href="#"
                  >
                    View Project
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Project Thumbnail"
                  className="rounded-t-md"
                  height={225}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold mb-2">Fitness Tracker App</h3>
                  <p className="text-gray-600 mb-4">A mobile app that helps users track their fitness goals.</p>
                  <div className="flex items-center gap-2 mb-4">
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">
                      React Native
                    </div>
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">Firebase</div>
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">Expo</div>
                  </div>
                  <Link
                    className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
                    href="#"
                  >
                    View Project
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-8">Work Projects</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <img
                  alt="Project Thumbnail"
                  className="rounded-t-md"
                  height={225}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold mb-2">Personal Finance App</h3>
                  <p className="text-gray-600 mb-4">
                    A web application that helps users manage their personal finances.
                  </p>
                  <div className="flex items-center gap-2 mb-4">
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">Vue.js</div>
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">Django</div>
                    <div className="bg-gray-200 px-2 py-1 rounded-md text-sm font-medium text-gray-700">PostgreSQL</div>
                  </div>
                  <Link
                    className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
                    href="#"
                  >
                    View Project
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-8">About Me</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h3 className="text-xl font-bold mb-4">Skills</h3>
                <ul className="text-gray-600 space-y-2">
                  <li>
                    <span className="font-bold">Front-end:</span>
                    React, Vue.js, HTML, CSS, JavaScript
                  </li>
                  <li>
                    <span className="font-bold">Back-end:</span>
                    Node.js, Express, Python, Django
                  </li>
                  <li>
                    <span className="font-bold">Databases:</span>
                    MongoDB, PostgreSQL, MySQL
                  </li>
                  <li>
                    <span className="font-bold">Tools:</span>
                    Git, GitHub, Figma, Photoshop
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-8">Connect with Me</h2>
            <div className="flex justify-center space-x-6">
              <Link className="text-gray-900 hover:text-gray-600" href="#">
                <div className="flex items-center gap-2">
                  <GithubIcon className="w-6 h-6" />
                  <span>Github</span>
                </div>
              </Link>
              <Link className="text-gray-900 hover:text-gray-600" href="#">
                <div className="flex items-center gap-2">
                  <LinkedinIcon className="w-6 h-6" />
                  <span>LinkedIn</span>
                </div>
              </Link>
              <Link className="text-gray-900 hover:text-gray-600" href="#">
                <div className="flex items-center gap-2">
                  <TwitterIcon className="w-6 h-6" />
                  <span>Twitter</span>
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container mx-auto px-6 md:px-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-8">Contact Me</h2>
            <form className="max-w-md mx-auto space-y-4">
              <div>
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" type="text" />
              </div>
              <div>
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div>
                <Label htmlFor="message">Message</Label>
                <Textarea className="min-h-[120px]" id="message" placeholder="Enter your message" />
              </div>
              <Button className="w-full" type="submit">
                Send Message
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-6 px-6 md:px-12">
        <div className="container mx-auto flex justify-between items-center">
          <p className="text-sm">© 2024 John Doe. All rights reserved.</p>
          <div className="flex space-x-4">
            <Link className="hover:text-gray-400" href="#">
              <GithubIcon className="w-5 h-5" />
            </Link>
            <Link className="hover:text-gray-400" href="#">
              <LinkedinIcon className="w-5 h-5" />
            </Link>
            <Link className="hover:text-gray-400" href="#">
              <TwitterIcon className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
