import Head from 'next/head'
import Image from 'next/image'
import icon from '@/images/icon.png'

const Header = () => {
  return (
    <div>
      <Head>
        <title>ufoo68 portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={icon} />
    </div>
  )
}

export default Header