import Head from 'next/head'

import { Tab, Tabs, Box } from '@mui/material'
import React from 'react'
import Profile from '@/components/Profile'
import Works from '@/components/Works'
import Sotial from '@/components/Sotial'
import { Work } from '@/libs/types'

type TabPanelProps = {
  children?: React.ReactNode;
  index: number;
  value: number;
}

type Props = {
  works: Work[]
}

const TabPanel = (props: TabPanelProps) => {
  const { children, value, index, ...other } = props

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box>
          {children}
        </Box>
      )}
    </div>
  );
}

const a11yProps = (index: number) => {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}


const Main = ({ works }: Props) => {
  const [tab, setTab] = React.useState(0)

  const handleChange = (_event: React.SyntheticEvent, newValue: number) => {
    setTab(newValue);
  };
  return (
    <div>
      <Head>
        <title>ufoo68 portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ textAlign: 'center' }}>
        <h1>ufoo68 portfolio</h1>
        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tabs value={tab}
            onChange={handleChange}
            aria-label="portfolio tab"
            centered
          >
            <Tab label="profile" {...a11yProps(0)} />
            <Tab label="works" {...a11yProps(1)} />
            <Tab label="Sotial" {...a11yProps(2)} />
            <Tab label="contact" {...a11yProps(2)} />
          </Tabs>
        </Box>
        <TabPanel value={tab} index={0}>
          <Profile />
        </TabPanel>
        <TabPanel value={tab} index={1}>
          <Works works={works} />
        </TabPanel>
        <TabPanel value={tab} index={2}>
          <Sotial />
        </TabPanel>
        <TabPanel value={tab} index={3}>
          Coming soon...
        </TabPanel>
      </Box>
    </div>
  )
}

export default Main