/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2pJrvALZwGJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Link from "next/link";
import { Menu } from "@/components/menu";
import { ProjectCard, SkillBadge, SkillGroup } from "@/components/ufoo-ui";
import { micrecmsClient, type Product, type Skill } from "@/components/utils";

export async function Main() {
	if (!micrecmsClient) {
		return <PortfolioContent products={[]} skills={[]} />;
	}

	const {
		contents: products,
	}: {
		contents: Product[];
	} =
		(await micrecmsClient.get({
			endpoint: "products",
			customRequestInit: { cache: "no-store" },
		})) ?? { contents: [] };
	const { contents: skills } = (await micrecmsClient.get({
		endpoint: "skills",
		customRequestInit: { cache: "no-store" },
	})) ?? { contents: [] };

	return <PortfolioContent products={products} skills={skills} />;
}

function PortfolioContent({
	products,
	skills,
}: {
	products: Product[];
	skills: Skill[];
}) {
	const currentYear = new Date().getFullYear();
	const workProducts = products.filter((product) => product.type[0] === "work");
	const personalProducts = products.filter(
		(product) => product.type[0] === "personal",
	);
	const languages = skills.filter((skill) => skill.type[0] === "language");
	const frameworks = skills.filter((skill) => skill.type[0] === "framework");
	const clouds = skills.filter((skill) => skill.type[0] === "cloud");
	const databases = skills.filter((skill) => skill.type[0] === "database");
	return (
		<div className="flex min-h-screen flex-col bg-ufoo-workspace text-ufoo-ink">
			<Menu />
			<main className="flex-1">
				<section
					id="top"
					className="overflow-hidden border-b border-ufoo-panel-border"
				>
					<div className="mx-auto grid min-h-[520px] w-full max-w-6xl items-center gap-10 px-5 py-16 sm:px-8 md:grid-cols-[1.1fr_0.9fr] md:py-20">
						<div className="max-w-2xl">
							<p className="mb-4 text-xs font-black uppercase tracking-[0.24em] text-ufoo-neon">
								Remote Web Developer
							</p>
							<h1 className="text-5xl font-black leading-tight tracking-tight text-ufoo-ink md:text-6xl">
								ufoo68 Portfolio
							</h1>
							<p className="mt-5 max-w-xl text-lg leading-7 text-ufoo-muted">
								滋賀からリモートワークでWEB開発をやっております。
							</p>
							<div className="mt-8 flex flex-wrap gap-3">
								<Link
									className="inline-flex h-12 items-center justify-center rounded-md bg-ufoo-neon px-6 text-base font-bold text-ufoo-dark transition hover:scale-105 hover:shadow-neon"
									href="#personal"
								>
									個人開発
								</Link>
								<Link
									className="inline-flex h-12 items-center justify-center rounded-md border-2 border-ufoo-neon px-6 text-base font-bold text-ufoo-neon transition hover:bg-ufoo-neon hover:text-ufoo-dark hover:shadow-neon"
									href="#work"
								>
									仕事での開発
								</Link>
							</div>
						</div>
						<div className="relative mx-auto hidden size-[360px] place-items-center md:grid">
							<div className="absolute inset-0 rounded-full border border-ufoo-neon/60 bg-ufoo-neon/10 shadow-neon" />
							<div className="absolute inset-8 rounded-full border border-ufoo-pink bg-ufoo-panel" />
							<img
								alt="Yuta Matsunaga"
								className="relative size-64 rounded-full border-2 border-ufoo-neon object-cover shadow-[0_18px_60px_rgba(0,0,0,0.35)]"
								height={256}
								src="/avatar.png"
								width={256}
							/>
						</div>
					</div>
				</section>
				<PortfolioShowcase
					id="personal"
					title="個人開発"
					eyebrow="Personal Projects"
					description="自分で課題を見つけ、企画から実装まで進めたプロダクトです。"
				>
					<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
						{personalProducts.map((product) => (
							<ProjectCard
								key={product.id}
								title={product.title}
								description={product.detail}
								eyebrow="personal"
								media={
									<img
										alt={product.title}
										className="h-full w-full object-cover"
										height={225}
										src={product.image.url}
										width={400}
									/>
								}
								technologies={product.technologies}
								action={
									<Link
										className="inline-flex h-10 items-center justify-center rounded-md bg-ufoo-neon px-4 text-sm font-bold text-ufoo-dark transition hover:shadow-neon"
										href={product.url}
									>
										詳細
									</Link>
								}
							/>
						))}
					</div>
				</PortfolioShowcase>
				<PortfolioShowcase
					id="work"
					title="仕事での開発"
					eyebrow="Client Work"
					description="業務で携わった開発経験を、担当領域と使った技術が見える形でまとめています。"
					muted
				>
					<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
						{workProducts.map((product) => (
							<ProjectCard
								key={product.id}
								title={product.title}
								description={product.detail}
								eyebrow="work"
								media={
									<img
										alt={product.title}
										className="h-full w-full object-cover"
										height={225}
										src={product.image.url}
										width={400}
									/>
								}
								technologies={product.technologies}
								action={
									<Link
										className="inline-flex h-10 items-center justify-center rounded-md bg-ufoo-neon px-4 text-sm font-bold text-ufoo-dark transition hover:shadow-neon"
										href={product.url}
									>
										詳細
									</Link>
								}
							/>
						))}
					</div>
				</PortfolioShowcase>
				<PortfolioShowcase
					id="skills"
					title="スキルセット"
					eyebrow="Skill Stack"
					description="開発で使ってきた技術をカテゴリごとに整理しています。"
				>
					<div className="grid md:grid-cols-2 gap-8">
						<SkillList title="言語" skills={languages} />
						<SkillList title="フレームワーク" skills={frameworks} />
						<SkillList title="クラウド" skills={clouds} />
						<SkillList title="データベース" skills={databases} />
					</div>
				</PortfolioShowcase>
				<PortfolioShowcase
					id="contact"
					title="問い合わせ"
					eyebrow="Contact"
					description="SNS からご連絡ください。"
					muted
				>
					<div className="max-w-md">
						<div className="rounded-lg border-l-4 border-ufoo-neon bg-ufoo-gray p-6 shadow-neon">
							<h3 className="text-xl font-black text-ufoo-neon">SNS</h3>
							<div className="mt-5 grid gap-3">
								<Link
									className="inline-flex items-center gap-3 rounded-md border border-ufoo-panel-border bg-white/8 px-4 py-3 font-bold text-ufoo-ink transition hover:border-ufoo-neon hover:text-ufoo-neon"
									href="https://github.com/ufoo68"
								>
									<GithubIcon className="w-6 h-6" />
									<span>Github</span>
								</Link>
								<Link
									className="inline-flex items-center gap-3 rounded-md border border-ufoo-panel-border bg-white/8 px-4 py-3 font-bold text-ufoo-ink transition hover:border-ufoo-neon hover:text-ufoo-neon"
									href="https://x.com/ufoo_yuta"
								>
									<XIcon className="w-6 h-6" />
									<span>X</span>
								</Link>
							</div>
						</div>
					</div>
				</PortfolioShowcase>
			</main>
			<footer className="border-t border-ufoo-panel-border bg-ufoo-dark px-5 py-6 text-ufoo-muted md:px-12">
				<div className="mx-auto flex max-w-6xl justify-between">
					<p className="text-sm">
						© {currentYear} ufoo68. All rights reserved.
					</p>
				</div>
			</footer>
		</div>
	);
}

function PortfolioShowcase({
	id,
	title,
	eyebrow,
	description,
	muted = false,
	children,
}: {
	id: string;
	title: string;
	eyebrow: string;
	description: string;
	muted?: boolean;
	children: React.ReactNode;
}) {
	return (
		<section
			id={id}
			className={`border-b border-ufoo-panel-border py-14 sm:py-20 ${
				muted ? "bg-ufoo-dark" : "bg-ufoo-workspace"
			}`}
		>
			<div className="mx-auto w-full max-w-6xl px-5 sm:px-8">
				<div className="mb-8 max-w-2xl sm:mb-10">
					<p className="mb-2 text-left text-xs font-black uppercase tracking-[0.22em] text-ufoo-neon">
						{eyebrow}
					</p>
					<h2 className="text-left text-3xl font-black tracking-tight text-ufoo-ink sm:text-4xl">
						{title}
					</h2>
					<p className="mt-3 text-left leading-7 text-ufoo-muted">
						{description}
					</p>
				</div>
				{children}
			</div>
		</section>
	);
}

function SkillList({ title, skills }: { title: string; skills: Skill[] }) {
	const currentYear = new Date().getFullYear();

	return (
		<SkillGroup title={title}>
			<div className="flex flex-wrap gap-3">
				{skills.map((skill) => (
					<SkillBadge
						key={skill.id}
						name={skill.title}
						meta={`${currentYear - skill.years}年`}
						tone="dark"
					/>
				))}
			</div>
		</SkillGroup>
	);
}

function GithubIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
			<path d="M9 18c-4.51 2-5-2-7-2" />
		</svg>
	);
}

function XIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="currentColor"
			aria-hidden="true"
		>
			<path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231 5.45-6.231Zm-1.161 17.52h1.833L7.084 4.126H5.117L17.083 19.77Z" />
		</svg>
	);
}
